config/routes.rb
Rails.application.routes.draw do

  resources :restaurants, only: [:index, :new, :create, :show] do

    resources :reviews, only: [:new, :create]

  end

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :reviews, dependent: :destroy
  validates :name , presence: true
  validates :address, presence: true
  # validates_presence_of:
  validates :category, inclusion:  { in: %w(chinese italian japanese french belgian)}
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, inclusion: { in: [0,1,2,3,4,5]}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [ :show ]

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new

  end

  def create
    @restaurant = Restaurant.create(restaurant_params)
    redirect_to restaurants_path
  end

  def show
    @reviews = @restaurant.reviews
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name,:address,:phone_number,:category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

def new
  @review = Review.new
  @restaurant = Restaurant.find(params[:restaurant_id])
end

def create

  @review = Review.new(restaurant_id: params[:restaurant_id], content: params[:content], rating: params[:rating])
  @review.save
  redirect_to restaurants_path
end

def review_params
    params.require(:review).permit(:content,:rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Restoapp</title>
   <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <%= stylesheet_link_tag "application" %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/restaurants/index.html.erb
<div class="container">
  <div class="row">
<% @restaurants.each do |restaurant| %>
  <h2><%= link_to restaurant.name, restaurant_path(restaurant) %></h2>
  <p><%= restaurant.address %></p>
  <p><%= restaurant.phone_number %></p>
  <p><%=  restaurant.category %></p>

<% end %>
  </div>
  </div>

app/views/restaurants/new.html.erb
<div class="container">
  <div class="row">
    <div class="text-center">

<%= bootstrap_form_for(@restaurant,layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-5") do |f| %>
  <%= f.text_field :name %>
  <%= f.text_field :address %>
  <%= f.text_field :phone_number %>
  <%= f.select :category, [["chinois", "chinese"], ["japanese"], ["french"],["belgian"],["italian"]] %>
  <%= f.submit "Create Restaurant", class: "btn btn-success" %>
<% end %>
</div>
</div>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <div class="row">
<p><%= @restaurant.name %></p>
<p><%= @restaurant.address %></p>
<p><%= @restaurant.phone_number %></p>
<p><%= @restaurant.category %></p>
<% @reviews.each  do |r| %>
<p><%= r.content %></p>
<% end %>
</div>
</div>

app/views/reviews/new.html.erb
<div class="container">
  <div class="row">
    <div class="text-center">

<%= bootstrap_form_for([@restaurant, @review], layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-5") do |f| %>
  <%= f.text_field :content %>
  <%= f.text_field :rating %>
  <%= f.submit "Create Review", class: "btn btn-success" %>
<% end %>
</div>
</div>
</div>